Changed sudo solbuild update unstable-x86-64
I changed it to sudo solbuild update unstable-x86_64 because when you try to update with unstable-x86-64, it gives you an error saying

Error: 'unstable-x86-64' is not a known profile
Valid profiles include:

* main-x86_64
* unstable-x86_64